"""add total_cost to orders

Revision ID: 5d9fcc20ead5
Revises: c97ae08bdb1c
Create Date: 2026-03-27 16:47:54.533403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9fcc20ead5'
down_revision: Union[str, Sequence[str], None] = 'c97ae08bdb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_cost')
    # ### end Alembic commands ###
